
package com.softwareaggov.messaging.service.soapclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RequestReplyProcessing", targetNamespace = "http://com.softwareaggov.messaging/jaxws/jms")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RequestReplyProcessing {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performMultiplicationFromStrings", targetNamespace = "http://com.softwareaggov.messaging/jaxws/jms", className = "com.softwareaggov.messaging.service.soapclient.PerformMultiplicationFromStrings")
    @ResponseWrapper(localName = "performMultiplicationFromStringsResponse", targetNamespace = "http://com.softwareaggov.messaging/jaxws/jms", className = "com.softwareaggov.messaging.service.soapclient.PerformMultiplicationFromStringsResponse")
    public String performMultiplicationFromStrings(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRandomNumber", targetNamespace = "http://com.softwareaggov.messaging/jaxws/jms", className = "com.softwareaggov.messaging.service.soapclient.GetRandomNumber")
    @ResponseWrapper(localName = "getRandomNumberResponse", targetNamespace = "http://com.softwareaggov.messaging/jaxws/jms", className = "com.softwareaggov.messaging.service.soapclient.GetRandomNumberResponse")
    public Long getRandomNumber();

}
