
package com.softwareaggov.messaging.service.soapclient.temp;

import javax.xml.namespace.QName;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RequestReplyProcessingBeanService", targetNamespace = "http://utils.service.messaging.softwareaggov.com/", wsdlLocation = "file:///Users/fabien.sanglier/MyDev/github-open-source/messaging-samples/j2ee-jms-examples/j2ee-jms-examples-client/ejb/src/main/resources/META-INF/wsdl/RequestReplyProcessingBean.wsdl")
public class RequestReplyProcessingBeanSoapJMSService
{

    private final static URL REQUESTREPLYPROCESSINGBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException REQUESTREPLYPROCESSINGBEANSERVICE_EXCEPTION;
    private final static QName REQUESTREPLYPROCESSINGBEANSERVICE_QNAME = new QName("http://utils.service.messaging.softwareaggov.com/", "RequestReplyProcessingBeanService");

    private final static String WSDL_LOCATION = "/META-INF/wsdl/RequestReplyOverJmsProcessingBean.wsdl";
    static {
        REQUESTREPLYPROCESSINGBEANSERVICE_WSDL_LOCATION = RequestReplyProcessingBeanSoapJMSService.class.getResource(WSDL_LOCATION);
        WebServiceException e = null;
        if (REQUESTREPLYPROCESSINGBEANSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '" + WSDL_LOCATION + "' wsdl. Place the resource correctly in the classpath.");
        }
        REQUESTREPLYPROCESSINGBEANSERVICE_EXCEPTION = e;
    }
}
