
package com.softwareaggov.messaging.service.soapclient.http;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RequestReplyHttpService", targetNamespace = "http://com.softwareaggov.messaging/j2ee-jms-examples/requestreply", wsdlLocation = "file:///Users/fabien.sanglier/MyDev/github-open-source/messaging-samples/j2ee-jms-examples/j2ee-jms-examples-client/ejb/src/main/resources/META-INF/wsdl/RequestReplyHttpService.wsdl")
public class RequestReplyHttpService
    extends Service
{

    private final static URL REQUESTREPLYHTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException REQUESTREPLYHTTPSERVICE_EXCEPTION;
    private final static QName REQUESTREPLYHTTPSERVICE_QNAME = new QName("http://com.softwareaggov.messaging/j2ee-jms-examples/requestreply", "RequestReplyHttpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:///Users/fabien.sanglier/MyDev/github-open-source/messaging-samples/j2ee-jms-examples/j2ee-jms-examples-client/ejb/src/main/resources/META-INF/wsdl/RequestReplyHttpService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REQUESTREPLYHTTPSERVICE_WSDL_LOCATION = url;
        REQUESTREPLYHTTPSERVICE_EXCEPTION = e;
    }

    public RequestReplyHttpService() {
        super(__getWsdlLocation(), REQUESTREPLYHTTPSERVICE_QNAME);
    }

    public RequestReplyHttpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REQUESTREPLYHTTPSERVICE_QNAME, features);
    }

    public RequestReplyHttpService(URL wsdlLocation) {
        super(wsdlLocation, REQUESTREPLYHTTPSERVICE_QNAME);
    }

    public RequestReplyHttpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REQUESTREPLYHTTPSERVICE_QNAME, features);
    }

    public RequestReplyHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RequestReplyHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RequestReplyPortType
     */
    @WebEndpoint(name = "RequestReplyHttpPort")
    public RequestReplyPortType getRequestReplyHttpPort() {
        return super.getPort(new QName("http://com.softwareaggov.messaging/j2ee-jms-examples/requestreply", "RequestReplyHttpPort"), RequestReplyPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RequestReplyPortType
     */
    @WebEndpoint(name = "RequestReplyHttpPort")
    public RequestReplyPortType getRequestReplyHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.softwareaggov.messaging/j2ee-jms-examples/requestreply", "RequestReplyHttpPort"), RequestReplyPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REQUESTREPLYHTTPSERVICE_EXCEPTION!= null) {
            throw REQUESTREPLYHTTPSERVICE_EXCEPTION;
        }
        return REQUESTREPLYHTTPSERVICE_WSDL_LOCATION;
    }

}
