
package com.softwareaggov.messaging.simplesoapjms.client.jaxws;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestWebServicePortType", targetNamespace = "http://soap.ejb.server.simplesoapjms.messaging.softwareaggov.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWebServicePortType {


    /**
     * 
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "processAndReply", targetNamespace = "http://soap.ejb.server.simplesoapjms.messaging.softwareaggov.com/", className = "com.softwareaggov.messaging.simplesoapjms.client.jaxws.ProcessAndReply")
    @ResponseWrapper(localName = "processAndReplyResponse", targetNamespace = "http://soap.ejb.server.simplesoapjms.messaging.softwareaggov.com/", className = "com.softwareaggov.messaging.simplesoapjms.client.jaxws.ProcessAndReplyResponse")
    @Action(input = "http://soap.ejb.server.simplesoapjms.messaging.softwareaggov.com/TestWebServicePortType/processAndReplyRequest", output = "http://soap.ejb.server.simplesoapjms.messaging.softwareaggov.com/TestWebServicePortType/processAndReplyResponse")
    public String processAndReply(
        @WebParam(name = "content", targetNamespace = "")
        String content);

    /**
     * 
     * @param content
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "processOneWay", targetNamespace = "http://soap.ejb.server.simplesoapjms.messaging.softwareaggov.com/", className = "com.softwareaggov.messaging.simplesoapjms.client.jaxws.ProcessOneWay")
    @Action(input = "http://soap.ejb.server.simplesoapjms.messaging.softwareaggov.com/TestWebServicePortType/processOneWay")
    public void processOneWay(
        @WebParam(name = "content", targetNamespace = "")
        String content);

}
